# EDA-2

# label encoder

In [7]:
import numpy as numpy
import pandas as pd 
from sklearn.preprocessing import LabelEncoder

In [8]:
data = pd.read_csv(r"C:\Users\91863\Downloads\iris.csv")

In [9]:
data.head()

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [10]:
# changes does not effect the data df

data1 = data.copy()

In [11]:
labelencoder = LabelEncoder()
data1.iloc[:,-1] = labelencoder.fit_transform(data1.iloc[:,-1])

C:\Users\91863\AppData\Local\Temp\ipykernel_5968\2928178228.py:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data1.iloc[:,-1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [12]:
data1

     Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             1           5.1          3.5           1.4          0.2        0
1             2           4.9          3.0           1.4          0.2        0
2             3           4.7          3.2           1.3          0.2        0
3             4           4.6          3.1           1.5          0.2        0
4             5           5.0          3.6           1.4          0.2        0
..          ...           ...          ...           ...          ...      ...
145         146           6.7          3.0           5.2          2.3        2
146         147           6.3          2.5           5.0          1.9        2
147         148           6.5          3.0           5.2          2.0        2
148         149           6.2          3.4           5.4          2.3        2
149         150           5.9          3.0           5.1          1.8        2

[150 rows x 6 columns]

# one hot encoder

using sklearn

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
data2 = data.copy()

In [15]:
data2.head()

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [16]:
# creating instance ofone-hot-encoder
enc = OneHotEncoder(handle_unknown = "ignore")

In [17]:
# pasing bridge -types- cat -colun (le values of bridge - types)
enc_df = pd.DataFrame(enc.fit_transform(data2[["Species"]]).toarray())

In [18]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [19]:
# merge with main df

data_final =  data2.iloc[:,0:4].join(enc_df)

In [20]:
data_final

     Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length    0    1    2
0             1           5.1          3.5           1.4  1.0  0.0  0.0
1             2           4.9          3.0           1.4  1.0  0.0  0.0
2             3           4.7          3.2           1.3  1.0  0.0  0.0
3             4           4.6          3.1           1.5  1.0  0.0  0.0
4             5           5.0          3.6           1.4  1.0  0.0  0.0
..          ...           ...          ...           ...  ...  ...  ...
145         146           6.7          3.0           5.2  0.0  0.0  1.0
146         147           6.3          2.5           5.0  0.0  0.0  1.0
147         148           6.5          3.0           5.2  0.0  0.0  1.0
148         149           6.2          3.4           5.4  0.0  0.0  1.0
149         150           5.9          3.0           5.1  0.0  0.0  1.0

[150 rows x 7 columns]

using pandas

In [21]:
data3 = data.copy()

In [22]:
data_encoded = pd.get_dummies(data3,dtype = int)

In [23]:
data_encoded

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,1,5.1,3.5,1.4,0.2,1,0,0
1,2,4.9,3.0,1.4,0.2,1,0,0
2,3,4.7,3.2,1.3,0.2,1,0,0
3,4,4.6,3.1,1.5,0.2,1,0,0
4,5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,0,0,1
146,147,6.3,2.5,5.0,1.9,0,0,1
147,148,6.5,3.0,5.2,2.0,0,0,1
148,149,6.2,3.4,5.4,2.3,0,0,1
149,150,5.9,3.0,5.1,1.8,0,0,1

# isolation Forest

In [24]:
from sklearn.ensemble import IsolationForest

In [25]:
# training model 
clf = IsolationForest(random_state=10,contamination=0.01)
clf.fit(data_encoded) # ranodom state - consistency ,contamination = % of data as outliers

IsolationForest(contamination=0.01, random_state=10)

In [26]:
# predictions

y_pred_outliers = clf.predict(data_encoded)

In [27]:
# -1 for outliers and 1 for inliers
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [28]:
data_encoded

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,1,5.1,3.5,1.4,0.2,1,0,0
1,2,4.9,3.0,1.4,0.2,1,0,0
2,3,4.7,3.2,1.3,0.2,1,0,0
3,4,4.6,3.1,1.5,0.2,1,0,0
4,5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,0,0,1
146,147,6.3,2.5,5.0,1.9,0,0,1
147,148,6.5,3.0,5.2,2.0,0,0,1
148,149,6.2,3.4,5.4,2.3,0,0,1
149,150,5.9,3.0,5.1,1.8,0,0,1

In [29]:
# lets add a new data point which is outlier

data_encoded.loc[150] = [151,20,30,40,50,1,0,0]

In [30]:
data_encoded

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,1,5.1,3.5,1.4,0.2,1,0,0
1,2,4.9,3.0,1.4,0.2,1,0,0
2,3,4.7,3.2,1.3,0.2,1,0,0
3,4,4.6,3.1,1.5,0.2,1,0,0
4,5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...,...
146,147,6.3,2.5,5.0,1.9,0,0,1
147,148,6.5,3.0,5.2,2.0,0,0,1
148,149,6.2,3.4,5.4,2.3,0,0,1
149,150,5.9,3.0,5.1,1.8,0,0,1
150,151,20.0,30.0,40.0,50.0,1,0,0

In [31]:
# training the model
clf = IsolationForest(random_state=10,contamination=0.01)
clf.fit(data_encoded)
#predictions

y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [32]:
data_encoded["scores"] = clf.decision_function(data_encoded)

In [33]:
data_encoded["anomaly"] = clf.decision_function(data_encoded.iloc[:,0:8])

In [34]:
data_encoded

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
0,1,5.1,3.5,1.4,0.2,1,0,0,0.114350,0.114350
1,2,4.9,3.0,1.4,0.2,1,0,0,0.113038,0.113038
2,3,4.7,3.2,1.3,0.2,1,0,0,0.106692,0.106692
3,4,4.6,3.1,1.5,0.2,1,0,0,0.119494,0.119494
4,5,5.0,3.6,1.4,0.2,1,0,0,0.140879,0.140879
...,...,...,...,...,...,...,...,...,...,...
146,147,6.3,2.5,5.0,1.9,0,0,1,0.088525,0.088525
147,148,6.5,3.0,5.2,2.0,0,0,1,0.115329,0.115329
148,149,6.2,3.4,5.4,2.3,0,0,1,0.063917,0.063917
149,150,5.9,3.0,5.1,1.8,0,0,1,0.094702,0.094702
150,151,20.0,30.0,40.0,50.0,1,0,0,-0.315800,-0.315800

In [36]:
#find  and print the outliers--anamoly
data_encoded[data_encoded["anomaly"]==-1]

Empty DataFrame
Columns: [Unnamed: 0, Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, Species_setosa, Species_versicolor, Species_virginica, scores, anomaly]
Index: []

PPS score

In [ ]:
!pip install ppscore

Collecting ppscore
  Downloading ppscore-1.3.0.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pandas<2.0.0,>=1.0.0 (from ppscore)
  Downloading pandas-1.5.3-cp310-cp310-win_amd64.whl (10.4 MB)
     ---------------------------------------- 0.0/10.4 MB ? eta -:--:--
      --------------------------------------- 0.1/10.4 MB 4.0 MB/s eta 0:00:03
     - -------------------------------------- 0.5/10.4 MB 4.8 MB/s eta 0:00:03
     -- ------------------------------------- 0.7/10.4 MB 5.3 MB/s eta 0:00:02
     ---- ----------------------------------- 1.1/10.4 MB 5.7 MB/s eta 0:00:02
     ---- ----------------------------------- 1.1/10.4 MB 5.7 MB/s eta 0:00:02
     ------ --------------------------------- 1.7/10.4 MB 5.6 MB/s eta 0:00:02
     ------ --------------------------------- 1.8/10.4 MB 5.0 MB/s eta 0:00:02
     ------- -------------------------------- 1.9/10.4 MB 4.8 MB/s eta 0:00:02
     ------- -------------------------------- 2.0/10.4 MB 4.3 MB/s eta 0:00:02
     -------- ------------------------------- 2.2/10.4 MB 4.4 MB/s eta 0:00:02
     -------- ------------------------------- 2.3/10.4 MB 4.0 MB/s eta 0:00:03
     --------- ------------------------------ 2.5/10.4 MB 4.0 MB/s eta 0:00:02
     --------- ------------------------------ 2.6/10.4 MB 3.9 MB/s eta 0:00:02
     ---------- ----------------------------- 2.7/10.4 MB 3.7 MB/s eta 0:00:03
     ---------- ----------------------------- 2.8/10.4 MB 3.6 MB/s eta 0:00:03
     ----------- ---------------------------- 2.9/10.4 MB 3.4 MB/s eta 0:00:03
     ----------- ---------------------------- 3.0/10.4 MB 3.3 MB/s eta 0:00:03
     ----------- ---------------------------- 3.0/10.4 MB 3.2 MB/s eta 0:00:03
     ----------- ---------------------------- 3.1/10.4 MB 3.0 MB/s eta 0:00:03
     ----------- ---------------------------- 3.1/10.4 MB 2.9 MB/s eta 0:00:03
     ------------ --------------------------- 3.1/10.4 MB 2.8 MB/s eta 0:00:03
     ------------ --------------------------- 3.2/10.4 MB 2.7 MB/s eta 0:00:03
     ------------ --------------------------- 3.2/10.4 MB 2.6 MB/s eta 0:00:03
     ------------ --------------------------- 3.3/10.4 MB 2.6 MB/s eta 0:00:03
     ------------ --------------------------- 3.3/10.4 MB 2.5 MB/s eta 0:00:03
     ------------- -------------------------- 3.4/10.4 MB 2.5 MB/s eta 0:00:03
     ------------- -------------------------- 3.4/10.4 MB 2.4 MB/s eta 0:00:03
     ------------- -------------------------- 3.5/10.4 MB 2.4 MB/s eta 0:00:03
     ------------- -------------------------- 3.5/10.4 MB 2.3 MB/s eta 0:00:03
     ------------- -------------------------- 3.6/10.4 MB 2.3 MB/s eta 0:00:03
     -------------- ------------------------- 3.7/10.4 MB 2.3 MB/s eta 0:00:03
     -------------- ------------------------- 3.8/10.4 MB 2.2 MB/s eta 0:00:03
     -------------- ------------------------- 3.9/10.4 MB 2.2 MB/s eta 0:00:03
     --------------- ------------------------ 3.9/10.4 MB 2.2 MB/s eta 0:00:03
     --------------- ------------------------ 4.0/10.4 MB 2.2 MB/s eta 0:00:03
     --------------- ------------------------ 4.1/10.4 MB 2.2 MB/s eta 0:00:03
     ---------------- ----------------------- 4.2/10.4 MB 2.2 MB/s eta 0:00:03
     ---------------- ----------------------- 4.3/10.4 MB 2.2 MB/s eta 0:00:03
     ---------------- ----------------------- 4.3/10.4 MB 2.2 MB/s eta 0:00:03
     ----------------- ---------------------- 4.4/10.4 MB 2.1 MB/s eta 0:00:03
     ----------------- ---------------------- 4.5/10.4 MB 2.1 MB/s eta 0:00:03
     ----------------- ---------------------- 4.6/10.4 MB 2.1 MB/s eta 0:00:03
     ------------------ --------------------- 4.8/10.4 MB 2.1 MB/s eta 0:00:03
     ------------------ --------------------- 4.9/10.4 MB 2.1 MB/s eta 0:00:03
     ------------------- -------------------- 5.0/10.4 MB 2.1 MB/s eta 0:00:03
     ------------------- -------------------- 5.1/10.4 MB 2.2 MB/s eta 0:00:03
     -------------------- ------------------- 5.3/10.4 MB 2.2 MB/s eta 0:00:03
     -------------------- ------------------- 5.4/10.4 MB 2.2 MB/s eta 0:00:03
     --------------------- ------------------ 5.6/10.4 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 5.7/10.4 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 5.9/10.4 MB 2.2 MB/s eta 0:00:02
     ----------------------- ---------------- 6.1/10.4 MB 2.3 MB/s eta 0:00:02
     ------------------------ --------------- 6.2/10.4 MB 2.3 MB/s eta 0:00:02
     ------------------------ --------------- 6.3/10.4 MB 2.3 MB/s eta 0:00:02
     ------------------------- -------------- 6.6/10.4 MB 2.3 MB/s eta 0:00:02
     -------------------------- ------------- 6.8/10.4 MB 2.3 MB/s eta 0:00:02
     -------------------------- ------------- 7.0/10.4 MB 2.4 MB/s eta 0:00:02
     --------------------------- ------------ 7.1/10.4 MB 2.4 MB/s eta 0:00:02
     ---------------------------- ----------- 7.3/10.4 MB 2.4 MB/s eta 0:00:02
     ---------------------------- ----------- 7.5/10.4 MB 2.4 MB/s eta 0:00:02
     ----------------------------- ---------- 7.6/10.4 MB 2.4 MB/s eta 0:00:02
     ------------------------------ --------- 7.8/10.4 MB 2.4 MB/s eta 0:00:02
     ------------------------------ --------- 8.0/10.4 MB 2.5 MB/s eta 0:00:01
     ------------------------------- -------- 8.1/10.4 MB 2.5 MB/s eta 0:00:01
     ------------------------------- -------- 8.3/10.4 MB 2.5 MB/s eta 0:00:01
     -------------------------------- ------- 8.5/10.4 MB 2.5 MB/s eta 0:00:01
     --------------------------------- ------ 8.7/10.4 MB 2.5 MB/s eta 0:00:01
     ---------------------------------- ----- 8.9/10.4 MB 2.5 MB/s eta 0:00:01
     ---------------------------------- ----- 9.1/10.4 MB 2.5 MB/s eta 0:00:01
     ----------------------------------- ---- 9.2/10.4 MB 2.5 MB/s eta 0:00:01
     ----------------------------------- ---- 9.3/10.4 MB 2.5 MB/s eta 0:00:01
     ------------------------------------ --- 9.4/10.4 MB 2.5 MB/s eta 0:00:01
     ------------------------------------ --- 9.5/10.4 MB 2.5 MB/s eta 0:00:01
     ------------------------------------ --- 9.6/10.4 MB 2.5 MB/s eta 0:00:01
     ------------------------------------ --- 9.6/10.4 MB 2.5 MB/s eta 0:00:01
     ------------------------------------- -- 9.6/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.6/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.7/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.4 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.2 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.2 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.2 MB/s eta 0:00:01
     ------------------------------------- -- 9.8/10.4 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 9.9/10.4 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 9.9/10.4 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 9.9/10.4 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 10.0/10.4 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 10.1/10.4 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  10.1/10.4 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  10.3/10.4 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  10.3/10.4 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  10.4/10.4 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  10.4/10.4 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 10.4/10.4 MB 2.0 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in c:\users\91863\appdata\roaming\python\python310\site-packages (from ppscore) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\91863\appdata\roaming\python\python310\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\91863\appdata\roaming\python\python310\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\91863\appdata\roaming\python\python310\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in c:\users\91863\appdata\roaming\python\python310\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.11.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\91863\appdata\roaming\python\python310\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\91863\appdata\roaming\python\python310\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.2.0)
Requirement already satisfied: six>=1.5 in c:\users\91863\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.16.0)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (setup.py): started
  Building wheel for ppscore (setup.py): finished with status 'done'
  Created wheel for ppscore: filename=ppscore-1.3.0-py2.py3-none-any.whl size=13201 sha256=d172421137bc06d6085800b6be93679a0aa2726ee3ca9730fad9f0667f0c3896
  Stored in directory: c:\users\91863\appdata\local\pip\cache\wheels\42\87\10\00056aa2d2624f1b9374db6a0d5245da9a3d87bdc9247c1a56
Successfully built ppscore
Installing collected packages: pandas, ppscore
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.1
    Uninstalling pandas-2.0.1:
      Successfully uninstalled pandas-2.0.1
Successfully installed pandas-1.5.3 ppscore-1.3.0

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\91863\AppData\Roaming\Python\Python310\site-packages\~andas'.
  You can safely remove it manually.

In [37]:
import ppscore as pps

In [39]:
# pps.score(df,"feature_column","target_column")  syntax
pps.score(data,"Sepal.Length","Petal.Length")

{'x': 'Sepal.Length',
 'y': 'Petal.Length',
 'ppscore': 0.550422595049248,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': 0.6692708968366863,
 'model': DecisionTreeRegressor()}

In [40]:
# calculate the whole pps matrix

pps.matrix(data)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Unnamed: 0,Unnamed: 0,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Unnamed: 0,Sepal.Length,0.202091,regression,True,mean absolute error,0.684667,0.546302,DecisionTreeRegressor()
2,Unnamed: 0,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.351938,DecisionTreeRegressor()
3,Unnamed: 0,Petal.Length,0.686620,regression,True,mean absolute error,1.488667,0.466518,DecisionTreeRegressor()
4,Unnamed: 0,Petal.Width,0.644777,regression,True,mean absolute error,0.644667,0.229001,DecisionTreeRegressor()
5,Unnamed: 0,Species,0.979345,classification,True,weighted F1,0.353333,0.986643,DecisionTreeClassifier()
6,Sepal.Length,Unnamed: 0,0.237121,regression,True,mean absolute error,37.500000,28.607972,DecisionTreeRegressor()
7,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
8,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
9,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
10,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
11,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,DecisionTreeClassifier()
12,Sepal.Width,Unnamed: 0,0.087208,regression,True,mean absolute error,37.500000,34.229701,DecisionTreeRegressor()
13,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
14,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
15,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
16,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
17,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,DecisionTreeClassifier()
18,Petal.Length,Unnamed: 0,0.555324,regression,True,mean absolute error,37.500000,16.675354,DecisionTreeRegressor()
19,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
20,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
21,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
22,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
23,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,DecisionTreeClassifier()
24,Petal.Width,Unnamed: 0,0.575272,regression,True,mean absolute error,37.500000,15.927291,DecisionTreeRegressor()
25,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
26,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
27,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
28,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
29,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,DecisionTreeClassifier()
30,Species,Unnamed: 0,0.665331,regression,True,mean absolute error,37.500000,12.550092,DecisionTreeRegressor()
31,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
32,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
33,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
34,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
35,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None

# Feature engineerinng

Univariate  Featuer selection

In [ ]:
# Featuer Extration with univariate staistical teste( CHI-square for clasiification)


from sklearn.feature_selection import SelectKBest
from sklearn.featuer_selection import chi2